// Pinned DTrait 1.0.31 F309 data. Extracted with SHA-checked, initialization-only VM.
export const EMOJI = [
  '😀',
  '☺',
  '🤵‍♂️',
  '♨',
  '☸',
  '⚧',
  '⁉',
  'ℹ',
  '🏳️‍⚧️',
  '🥲',
  '☹',
  '☠',
  '🧑‍🦰',
  '🧏‍♂️',
  '⛷',
  '🧑‍🤝‍🧑',
  '☘',
  '⛰',
  '⛩',
  '⛴',
  '✈',
  '⏱',
  '⛈',
  '☂',
  '⛱',
  '☃',
  '☄',
  '⛸',
  '♟',
  '⛑',
  '⌨',
  '✉',
  '✏',
  '👩‍❤️‍💋‍👨',
  '👨‍👩‍👧‍👦',
  '👨‍👩‍👦',
  '😀',
  '©',
  '®',
  '™',
  '👁️‍🗨️',
  '✒',
  '✂',
  '⛏',
  '⚒',
  '⚔',
  '⚙',
  '⛓',
  '⚗',
  '⚰',
  '⚱',
  '⚠',
  '☢',
  '☣',
  '⬆',
  '↗',
  '➡',
  '⬅',
  '⚛',
  '✡',
  '✝',
  '☦',
  '▶',
  '⏭',
  '⏯',
  '⏏',
  '♀',
  '♂',
  '✖',
  '〰',
  '⚕',
  '⚜',
  '✔',
  '✳',
  '❇',
  '◼',
  '▪',
  '❣',
  '❤',
  '✌',
  '☝',
  '✍',
  '❄',
  '⚖',
  '↪',
  '☯',
  '☪',
  '☮',
  '☑',
  '✴',
  '🅰',
  '🅿',
] as const;
export const FONT_STYLE =
  "\n\t'Segoe Fluent Icons',\n\t'Ink Free',\n\t'Bahnschrift',\n\t'Segoe MDL2 Assets',\n\t'HoloLens MDL2 Assets',\n\t'Leelawadee UI',\n\t'Javanese Text',\n\t'Segoe UI Emoji',\n\t'Aldhabi',\n\t'Gadugi',\n\t'Myanmar Text',\n\t'Nirmala UI',\n\t'Lucida Console',\n\t'Cambria Math',\n\t'Bai Jamjuree',\n\t'Chakra Petch',\n\t'Charmonman',\n\t'Fahkwang',\n\t'K2D',\n\t'Kodchasan',\n\t'KoHo',\n\t'Sarabun',\n\t'Srisakdi',\n\t'Galvji',\n\t'MuktaMahee Regular',\n\t'InaiMathi Bold',\n\t'American Typewriter Semibold',\n\t'Futura Bold',\n\t'SignPainter-HouseScript Semibold',\n\t'PingFang HK Light',\n\t'Kohinoor Devanagari Medium',\n\t'Luminari',\n\t'Geneva',\n\t'Helvetica Neue',\n\t'Droid Sans Mono',\n\t'Dancing Script',\n\t'Roboto',\n\t'Ubuntu',\n\t'Liberation Mono',\n\t'Source Code Pro',\n\t'DejaVu Sans',\n\t'OpenSymbol',\n\t'Chilanka',\n\t'Cousine',\n\t'Arimo',\n\t'Jomolhari',\n\t'MONO',\n\t'Noto Color Emoji',\n\tsans-serif !important\n" as const;
export const WINDOWS_FONTS = {
  '7': ['Cambria Math', 'Lucida Console'],
  '8': ['Aldhabi', 'Gadugi', 'Myanmar Text', 'Nirmala UI'],
  '10': [
    'HoloLens MDL2 Assets',
    'Segoe MDL2 Assets',
    'Bahnschrift',
    'Ink Free',
  ],
  '11': ['Segoe Fluent Icons'],
  '8.1': ['Leelawadee UI', 'Javanese Text', 'Segoe UI Emoji'],
} as const;
export const APPLE_FONTS = {
  '12': [
    'Noto Sans Gunjala Gondi Regular',
    'Noto Sans Masaram Gondi Regular',
    'Noto Serif Yezidi Regular',
  ],
  '13': [
    'Apple SD Gothic Neo ExtraBold',
    'STIX Two Math Regular',
    'STIX Two Text Regular',
    'Noto Sans Canadian Aboriginal Regular',
  ],
  '10.9': ['Helvetica Neue', 'Geneva'],
  '10.10': ['Kohinoor Devanagari Medium', 'Luminari'],
  '10.11': ['PingFang HK Light'],
  '10.12': [
    'American Typewriter Semibold',
    'Futura Bold',
    'SignPainter-HouseScript Semibold',
  ],
  '10.13-10.14': ['InaiMathi Bold'],
  '10.15-11': ['Galvji', 'MuktaMahee Regular'],
} as const;
export const CANDIDATE_FONTS = [
  'Aldhabi',
  'American Typewriter Semibold',
  'Amiri',
  'Apple SD Gothic Neo ExtraBold',
  'Arimo',
  'Bahnschrift',
  'Cambria Math',
  'Chilanka',
  'Cousine',
  'Dancing Script',
  'DejaVu Sans',
  'Droid Sans Mono',
  'Futura Bold',
  'Gadugi',
  'Galvji',
  'Geneva',
  'Gentium Book Basic',
  'Helvetica Neue',
  'HoloLens MDL2 Assets',
  'InaiMathi Bold',
  'Ink Free',
  'Javanese Text',
  'Jomolhari',
  'KACSTOffice',
  'Kohinoor Devanagari Medium',
  'Leelawadee UI',
  'Liberation Mono',
  'Lucida Console',
  'Luminari',
  'MONO',
  'MS Outlook',
  'MuktaMahee Regular',
  'Myanmar Text',
  'Nirmala UI',
  'Noto Color Emoji',
  'Noto Sans Canadian Aboriginal Regular',
  'Noto Sans Gunjala Gondi Regular',
  'Noto Sans Masaram Gondi Regular',
  'Noto Serif Yezidi Regular',
  'OpenSymbol',
  'PingFang HK Light',
  'Roboto',
  'STIX Two Math Regular',
  'STIX Two Text Regular',
  'Segoe Fluent Icons',
  'Segoe MDL2 Assets',
  'Segoe UI Emoji',
  'SignPainter-HouseScript Semibold',
  'Source Code Pro',
  'Ubuntu',
  'ZWAdobeF',
] as const;
